blueprint:
  name: Simple Adaptive Room Lighting
  description: >
    Lightweight adaptive lighting blueprint.
    It updates brightness and white temperature from sun elevation, for the lights
    currently on in a room.
    Manual control is handled with a dedicated input_boolean: when off, adaptive
    updates are paused; when on, updates resume.
  domain: automation
  input:
    target_lights:
      name: Target lights
      description: Lights controlled by this automation instance.
      selector:
        entity:
          domain: light
          multiple: true

    auto_mode_boolean:
      name: Adaptive auto mode
      description: input_boolean controlling adaptive mode (on = adaptive active, off = manual mode).
      selector:
        entity:
          domain: input_boolean

    update_interval_min:
      name: Update interval (minutes)
      description: Re-apply adaptive values every N minutes.
      default: 2
      selector:
        number:
          min: 1
          max: 30
          step: 1
          mode: slider
          unit_of_measurement: min

    transition_sec:
      name: Transition duration (seconds)
      default: 2
      selector:
        number:
          min: 0
          max: 120
          step: 1
          mode: slider
          unit_of_measurement: s

    brightness_night:
      name: Brightness at night (%)
      default: 10
      selector:
        number:
          min: 1
          max: 100
          step: 1
          mode: slider
          unit_of_measurement: "%"

    brightness_day:
      name: Brightness at day peak (%)
      default: 85
      selector:
        number:
          min: 1
          max: 100
          step: 1
          mode: slider
          unit_of_measurement: "%"

    kelvin_night:
      name: Kelvin at night
      default: 2200
      selector:
        number:
          min: 1800
          max: 5000
          step: 50
          mode: slider
          unit_of_measurement: K

    kelvin_day:
      name: Kelvin at day peak
      default: 5000
      selector:
        number:
          min: 2200
          max: 9000
          step: 50
          mode: slider
          unit_of_measurement: K

mode: single

variables:
  room_lights: !input target_lights
  auto_mode_entity: !input auto_mode_boolean
  interval_min: !input update_interval_min
  fade_s: !input transition_sec
  b_night: !input brightness_night
  b_day: !input brightness_day
  k_night: !input kelvin_night
  k_day: !input kelvin_day
  light_entities: >
    {% if room_lights is string %}
      {{ [room_lights] }}
    {% else %}
      {{ room_lights | list }}
    {% endif %}

trigger:
  - platform: time_pattern
    minutes: "/1"
    id: tick

  - platform: state
    entity_id: !input target_lights
    to: "on"
    id: light_on

  - platform: state
    entity_id: !input auto_mode_boolean
    to: "on"
    id: auto_on

  - platform: sun
    event: sunrise
    id: sun_event

  - platform: sun
    event: sunset
    id: sun_event

condition:
  - condition: state
    entity_id: !input auto_mode_boolean
    state: "on"

  - condition: template
    value_template: >
      {{ trigger.id != 'tick' or (now().minute % (interval_min | int(2)) == 0) }}

action:
  - variables:
      on_lights: >
        {{ expand(light_entities)
           | selectattr('state', 'eq', 'on')
           | map(attribute='entity_id')
           | list }}

  - condition: template
    value_template: "{{ on_lights | count > 0 }}"

  - variables:
      elevation: "{{ state_attr('sun.sun', 'elevation') | float(-6) }}"
      # Map sun elevation from [-6 .. 60] to [0 .. 1].
      ratio: >
        {% set raw = (elevation + 6) / 66 %}
        {{ [0, [raw, 1] | min] | max }}
      target_brightness: >
        {{ (b_night | float(10) + (b_day | float(85) - b_night | float(10)) * (ratio | float(0)))
           | round(0) | int }}
      target_kelvin: >
        {{ (k_night | float(2200) + (k_day | float(5000) - k_night | float(2200)) * (ratio | float(0)))
           | round(0) | int }}

  - service: light.turn_on
    target:
      entity_id: "{{ on_lights }}"
    data:
      brightness_pct: "{{ target_brightness }}"
      kelvin: "{{ target_kelvin }}"
      transition: "{{ fade_s | int(2) }}"
