blueprint:
  name: Simple Adaptive Room Lighting
  description: >
    Lightweight adaptive lighting blueprint.
    It updates brightness and white temperature from sun elevation, for the lights
    currently on in a room.
    Manual control is handled with a dedicated input_boolean: when off, adaptive
    updates are paused; when on, updates resume.
  domain: automation
  homeassistant:
    min_version: 2024.6.0
  input:
    target_lights:
      name: Target lights
      description: Lights controlled by this automation instance.
      selector:
        entity:
          domain: light
          multiple: true

    adaptive_settings:
      name: Adaptive settings
      icon: mdi:tune-vertical
      input:
        update_interval_min:
          name: Update interval (minutes)
          description: Re-apply adaptive values every N minutes.
          default: 2
          selector:
            number:
              min: 1
              max: 30
              step: 1
              mode: slider
              unit_of_measurement: min

        transition_sec:
          name: Transition duration (seconds)
          default: 10
          selector:
            number:
              min: 0
              max: 120
              step: 1
              mode: slider
              unit_of_measurement: s

        brightness_night:
          name: Brightness at night (%)
          default: 30
          selector:
            number:
              min: 1
              max: 100
              step: 1
              mode: slider
              unit_of_measurement: "%"

        brightness_day:
          name: Brightness at day peak (%)
          default: 100
          selector:
            number:
              min: 1
              max: 100
              step: 1
              mode: slider
              unit_of_measurement: "%"

        kelvin_night:
          name: Kelvin at night
          default: 2700
          selector:
            number:
              min: 1800
              max: 5000
              step: 50
              mode: slider
              unit_of_measurement: K

        kelvin_day:
          name: Kelvin at day peak
          default: 5500
          selector:
            number:
              min: 2200
              max: 9000
              step: 50
              mode: slider
              unit_of_measurement: K

        day_span_adjustment_min:
          name: Day span adjustment (minutes)
          description: "Extend the adaptive day beyond sun events (+) or shorten it (-). Example: -60 starts 60 min later and ends 60 min earlier."
          default: 60
          selector:
            number:
              min: -120
              max: 120
              step: 5
              mode: slider
              unit_of_measurement: min

    auto_mode_section:
      name: Optional auto mode input
      icon: mdi:toggle-switch
      collapsed: true
      input:
        enable_auto_mode:
          name: Enable auto mode input_boolean
          description: Tick to enable manual pause/resume via an input_boolean.
          default: false
          selector:
            boolean:

        auto_mode_boolean:
          name: Adaptive auto mode entity
          description: input_boolean controlling adaptive mode (on = adaptive active, off = manual mode).
          default: ""
          selector:
            entity:
              domain: input_boolean

mode: restart

variables:
  room_lights: !input target_lights
  auto_mode_enabled: !input enable_auto_mode
  auto_mode_input_entity: !input auto_mode_boolean
  interval_min: !input update_interval_min
  fade_s: !input transition_sec
  b_night: !input brightness_night
  b_day: !input brightness_day
  k_night: !input kelvin_night
  k_day: !input kelvin_day
  day_span_adjustment_min: !input day_span_adjustment_min
  light_entities: >
    {% if room_lights is string %}
      {{ [room_lights] }}
    {% else %}
      {{ room_lights | list }}
    {% endif %}

trigger:
  - platform: time_pattern
    # Keep a 1-minute heartbeat, then filter with interval_min in conditions.
    # Using "*" avoids frontend trigger-description issues seen with "/1" on some HA builds.
    minutes: "*"
    id: tick

  # Re-apply immediately when adaptive auto mode is re-enabled.
  - platform: state
    entity_id: !input auto_mode_boolean
    from: "off"
    to: "on"
    id: auto_mode_enabled
    enabled: !input enable_auto_mode

  # Re-apply immediately after automation reload/save in HA UI.
  - platform: event
    event_type: automation_reloaded
    id: automation_reloaded

  - platform: state
    entity_id: !input target_lights
    to: "on"
    id: light_on

  - platform: sun
    event: sunrise
    id: sun_event

  - platform: sun
    event: sunset
    id: sun_event

condition:
  - condition: template
    value_template: >
      {{ not auto_mode_enabled
         or auto_mode_input_entity in ['', none]
         or is_state(auto_mode_input_entity, 'on') }}

  - condition: template
    value_template: >
      {{ trigger.id != 'tick' or (now().minute % (interval_min | int(2)) == 0) }}

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'light_on' }}"
        sequence:
          - delay:
              milliseconds: 800

  - variables:
      on_lights: >
        {{ expand(light_entities)
           | selectattr('state', 'eq', 'on')
           | map(attribute='entity_id')
           | list }}
      target_lights_to_update: >
        {% if trigger.id == 'light_on' and trigger.entity_id in light_entities %}
          {{ ([trigger.entity_id] + on_lights) | unique | list }}
        {% else %}
          {{ on_lights }}
        {% endif %}
      applied_transition_s: "{{ fade_s | int(2) }}"

  - condition: template
    value_template: "{{ target_lights_to_update | count > 0 }}"

  - variables:
      now_ts: "{{ as_timestamp(now()) }}"
      next_rising_ts: "{{ as_timestamp(state_attr('sun.sun', 'next_rising')) }}"
      next_setting_ts: "{{ as_timestamp(state_attr('sun.sun', 'next_setting')) }}"
      day_offset_s: "{{ day_span_adjustment_min | float(0) * 60 }}"
      adjusted_sunrise_ts: >
        {% if next_rising_ts and next_setting_ts %}
          {% set nr = next_rising_ts | float(0) %}
          {% set ns = next_setting_ts | float(0) %}
          {% set o = day_offset_s | float(0) %}
          {{ (nr - (86400 if nr > ns else 0)) - o }}
        {% else %}
          {{ none }}
        {% endif %}
      adjusted_sunset_ts: >
        {% if next_rising_ts and next_setting_ts %}
          {{ (next_setting_ts | float(0)) + (day_offset_s | float(0)) }}
        {% else %}
          {{ none }}
        {% endif %}
      previous_adjusted_sunrise_ts: >
        {% if adjusted_sunrise_ts is not none %}
          {{ (adjusted_sunrise_ts | float(0)) - 86400 }}
        {% else %}
          {{ none }}
        {% endif %}
      previous_adjusted_sunset_ts: >
        {% if adjusted_sunset_ts is not none %}
          {{ (adjusted_sunset_ts | float(0)) - 86400 }}
        {% else %}
          {{ none }}
        {% endif %}
      brightness_plateau_target_s: 21600
      brightness_edge_s: 900
      smoothstep_gain: 1.4
      smoothstep_num_offset: 27
      smoothstep_den_multiplier: 9
      # Adaptive day span:
      # +offset => sunrise earlier + sunset later (longer day)
      # -offset => sunrise later + sunset earlier (shorter day)
      # sun_position in [-1, 1]: 0 at adjusted sunrise/sunset, +1 at adjusted noon, -1 at adjusted midnight.
      sun_position: >
        {% if adjusted_sunrise_ts is not none and adjusted_sunset_ts is not none %}
          {% set t = now_ts | float(0) %}
          {% set sr0 = adjusted_sunrise_ts | float(0) %}
          {% set ss0 = adjusted_sunset_ts | float(0) %}
          {% set sr_prev = previous_adjusted_sunrise_ts | float(0) %}
          {% set ss_prev = previous_adjusted_sunset_ts | float(0) %}
          {% if t >= sr0 and t < ss0 %}
            {% set day_start = sr0 %}
            {% set day_end = ss0 %}
            {% set d = (t - day_start) / (day_end - day_start) %}
            {% set d = [0, [d, 1] | min] | max %}
            {{ (1 - ((2 * d - 1) ** 2)) | float(0) }}
          {% elif t >= sr_prev and t < ss_prev %}
            {% set day_start = sr_prev %}
            {% set day_end = ss_prev %}
            {% set d = (t - day_start) / (day_end - day_start) %}
            {% set d = [0, [d, 1] | min] | max %}
            {{ (1 - ((2 * d - 1) ** 2)) | float(0) }}
          {% elif t < sr0 %}
            {% set night_start = ss_prev %}
            {% set night_end = sr0 %}
            {% set n = (t - night_start) / (night_end - night_start) %}
            {% set n = [0, [n, 1] | min] | max %}
            {{ (-(1 - ((2 * n - 1) ** 2))) | float(0) }}
          {% else %}
            {% set night_start = ss0 %}
            {% set night_end = sr0 + 86400 %}
            {% set n = (t - night_start) / (night_end - night_start) %}
            {% set n = [0, [n, 1] | min] | max %}
            {{ (-(1 - ((2 * n - 1) ** 2))) | float(0) }}
          {% endif %}
        {% else %}
          0
        {% endif %}
      target_brightness: >
        {% set b_min = [b_night | float(1), b_day | float(100)] | min %}
        {% set b_max = [b_night | float(1), b_day | float(100)] | max %}
        {% set t = now_ts | float(0) %}
        {% set sr0 = adjusted_sunrise_ts | float(0) %}
        {% set ss0 = adjusted_sunset_ts | float(0) %}
        {% set sr_prev = previous_adjusted_sunrise_ts | float(0) %}
        {% set ss_prev = previous_adjusted_sunset_ts | float(0) %}
        {% set plateau_target_s = brightness_plateau_target_s | float(21600) %}
        {% set edge_s = brightness_edge_s | float(900) %}
        {% set gain = smoothstep_gain | float(1.4) %}
        {% set num_offset = smoothstep_num_offset | float(27) %}
        {% set den_multiplier = smoothstep_den_multiplier | float(9) %}
        {% if t >= sr0 and t < ss0 %}
          {% set day_sr = sr0 %}
          {% set day_ss = ss0 %}
        {% elif t >= sr_prev and t < ss_prev %}
          {% set day_sr = sr_prev %}
          {% set day_ss = ss_prev %}
        {% else %}
          {% set day_sr = none %}
          {% set day_ss = none %}
        {% endif %}
        {% if day_sr is none %}
          {{ b_min | round(0) | int }}
        {% else %}
          {% set day_len_s = day_ss - day_sr %}
          {% set ramp_s = [0, (day_len_s - plateau_target_s) / 2] | max %}
          {% set up_start = day_sr - edge_s %}
          {% set up_end = day_sr + ramp_s %}
          {% set down_start = day_ss - ramp_s %}
          {% set down_end = day_ss + edge_s %}
          {% if t < up_start %}
            {% set b = b_min %}
          {% elif t <= up_end %}
            {% set u = (t - up_start) / (up_end - up_start) %}
            {% set u = [0, [u, 1] | min] | max %}
            {% set z = (2 * u) - 1 %}
            {% set az = gain * z %}
            {% set z2 = az * az %}
            {% set tnh = (az * (num_offset + z2)) / (num_offset + (den_multiplier * z2)) %}
            {% set s = (tnh + 1) / 2 %}
            {% set b = b_min + (b_max - b_min) * s %}
          {% elif t < down_start %}
            {% set b = b_max %}
          {% elif t <= down_end %}
            {% set u = (t - down_start) / (down_end - down_start) %}
            {% set u = [0, [u, 1] | min] | max %}
            {% set z = (2 * u) - 1 %}
            {% set az = gain * z %}
            {% set z2 = az * az %}
            {% set tnh = (az * (num_offset + z2)) / (num_offset + (den_multiplier * z2)) %}
            {% set s = (tnh + 1) / 2 %}
            {% set b = b_max - (b_max - b_min) * s %}
          {% else %}
            {% set b = b_min %}
          {% endif %}
          {{ [b_min, [b, b_max] | min] | max | round(0) | int }}
        {% endif %}
      target_kelvin: >
        {% set p = sun_position | float(0) %}
        {% set k_min = [k_night | float(2200), k_day | float(5000)] | min %}
        {% set k_max = [k_night | float(2200), k_day | float(5000)] | max %}
        {% if p > 0 %}
          {{ ((k_max - k_min) * p + k_min) | round(0) | int }}
        {% else %}
          {{ k_min | round(0) | int }}
        {% endif %}

  - repeat:
      for_each: "{{ target_lights_to_update }}"
      sequence:
        - variables:
            modes: "{{ state_attr(repeat.item, 'supported_color_modes') or [] }}"
            min_k: "{{ state_attr(repeat.item, 'min_color_temp_kelvin') | float(0) }}"
            max_k: "{{ state_attr(repeat.item, 'max_color_temp_kelvin') | float(0) }}"
            has_brightness_attr: "{{ state_attr(repeat.item, 'brightness') is not none }}"
            supports_ct: >
              {{ 'color_temp' in modes
                 or (min_k > 0 and max_k > 0)
                 or (state_attr(repeat.item, 'color_temp_kelvin') is not none)
                 or (state_attr(repeat.item, 'color_temp') is not none) }}
            # In Z2M/groups, supported_color_modes can be empty or partial.
            # Default to brightness-capable unless explicitly onoff-only.
            supports_brightness: >
              {{ has_brightness_attr
                 or (modes | count == 0)
                 or not ((modes | count == 1) and (modes[0] == 'onoff')) }}
            clamped_kelvin: >
              {% if min_k > 0 and max_k > 0 %}
                {{ [min_k, [target_kelvin | float(0), max_k] | min] | max | round(0) | int }}
              {% else %}
                {{ target_kelvin | int(0) }}
              {% endif %}
        - variables:
            turn_on_data_json: >
              {% set transition_value = applied_transition_s | int(2) %}
              {% if supports_brightness and supports_ct %}
                {{ {'transition': transition_value, 'brightness_pct': target_brightness, 'color_temp_kelvin': clamped_kelvin} | to_json }}
              {% elif supports_brightness %}
                {{ {'transition': transition_value, 'brightness_pct': target_brightness} | to_json }}
              {% elif supports_ct %}
                {{ {'transition': transition_value, 'color_temp_kelvin': clamped_kelvin} | to_json }}
              {% else %}
                {{ {'transition': transition_value} | to_json }}
              {% endif %}
        - service: light.turn_on
          target:
            entity_id: "{{ repeat.item }}"
          data: "{{ turn_on_data_json | from_json }}"
