blueprint:
  name: Simple Adaptive Room Lighting
  description: >
    Lightweight adaptive lighting blueprint.
    It updates brightness and white temperature from sun elevation, for the lights
    currently on in a room.
    Manual control is handled with a dedicated input_boolean: when off, adaptive
    updates are paused; when on, updates resume.
  domain: automation
  input:
    target_lights:
      name: Target lights
      description: Lights controlled by this automation instance.
      selector:
        entity:
          domain: light
          multiple: true

    auto_mode_boolean:
      name: Adaptive auto mode
      description: Optional input_boolean controlling adaptive mode (on = adaptive active, off = manual mode).
      default: ""
      selector:
        entity:
          domain: input_boolean

    update_interval_min:
      name: Update interval (minutes)
      description: Re-apply adaptive values every N minutes.
      default: 2
      selector:
        number:
          min: 1
          max: 30
          step: 1
          mode: slider
          unit_of_measurement: min

    transition_sec:
      name: Transition duration (seconds)
      default: 2
      selector:
        number:
          min: 0
          max: 120
          step: 1
          mode: slider
          unit_of_measurement: s

    brightness_night:
      name: Brightness at night (%)
      default: 10
      selector:
        number:
          min: 1
          max: 100
          step: 1
          mode: slider
          unit_of_measurement: "%"

    brightness_day:
      name: Brightness at day peak (%)
      default: 85
      selector:
        number:
          min: 1
          max: 100
          step: 1
          mode: slider
          unit_of_measurement: "%"

    kelvin_night:
      name: Kelvin at night
      default: 2200
      selector:
        number:
          min: 1800
          max: 5000
          step: 50
          mode: slider
          unit_of_measurement: K

    kelvin_day:
      name: Kelvin at day peak
      default: 5000
      selector:
        number:
          min: 2200
          max: 9000
          step: 50
          mode: slider
          unit_of_measurement: K

    peak_plateau_min:
      name: Peak plateau half-width (minutes)
      description: Legacy setting (unused with Adaptive Lighting default algorithm).
      default: 60
      selector:
        number:
          min: 0
          max: 240
          step: 5
          mode: slider
          unit_of_measurement: min

    sun_offset_min:
      name: Sun offset (minutes)
      description: Shift adaptation timing relative to sun events (+ = earlier, - = later).
      default: 0
      selector:
        number:
          min: -120
          max: 120
          step: 5
          mode: slider
          unit_of_measurement: min


mode: restart

variables:
  room_lights: !input target_lights
  auto_mode_entity: !input auto_mode_boolean
  interval_min: !input update_interval_min
  fade_s: !input transition_sec
  b_night: !input brightness_night
  b_day: !input brightness_day
  k_night: !input kelvin_night
  k_day: !input kelvin_day
  sun_offset_min: !input sun_offset_min
  light_entities: >
    {% if room_lights is string %}
      {{ [room_lights] }}
    {% else %}
      {{ room_lights | list }}
    {% endif %}

trigger:
  - platform: time_pattern
    minutes: "/1"
    id: tick

  - platform: state
    entity_id: !input target_lights
    to: "on"
    id: light_on

  - platform: sun
    event: sunrise
    id: sun_event

  - platform: sun
    event: sunset
    id: sun_event

condition:
  - condition: template
    value_template: >
      {{ auto_mode_entity in ['', none] or is_state(auto_mode_entity, 'on') }}

  - condition: template
    value_template: >
      {{ trigger.id != 'tick' or (now().minute % (interval_min | int(2)) == 0) }}

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'light_on' }}"
        sequence:
          - delay:
              milliseconds: 800

  - variables:
      on_lights: >
        {{ expand(light_entities)
           | selectattr('state', 'eq', 'on')
           | map(attribute='entity_id')
           | list }}
      target_lights_to_update: >
        {% if trigger.id == 'light_on' and trigger.entity_id in light_entities %}
          {{ ([trigger.entity_id] + on_lights) | unique | list }}
        {% else %}
          {{ on_lights }}
        {% endif %}

  - condition: template
    value_template: "{{ target_lights_to_update | count > 0 }}"

  - variables:
      n_ts: "{{ as_timestamp(now()) }}"
      n_shifted_ts: "{{ (as_timestamp(now()) | float(0)) + (sun_offset_min | float(0) * 60) }}"
      nr_ts: "{{ as_timestamp(state_attr('sun.sun', 'next_rising')) }}"
      ns_ts: "{{ as_timestamp(state_attr('sun.sun', 'next_setting')) }}"
      nn_ts: "{{ as_timestamp(state_attr('sun.sun', 'next_noon')) }}"
      nm_ts: "{{ as_timestamp(state_attr('sun.sun', 'next_midnight')) }}"
      # Adaptive Lighting default sun position in [-1, 1]:
      # -1 at midnight, 0 at sunrise/sunset, +1 at solar noon.
      sun_position: >
        {% if nr_ts and ns_ts and nn_ts and nm_ts %}
          {% set t = n_shifted_ts | float(0) %}
          {% set nr = nr_ts | float(0) %}
          {% set ns = ns_ts | float(0) %}
          {% set nn = nn_ts | float(0) %}
          {% set nm = nm_ts | float(0) %}
          {% set prev_nr = nr - 86400 %}
          {% set prev_ns = ns - 86400 %}
          {% set prev_nn = nn - 86400 %}
          {% set prev_nm = nm - 86400 %}
          {% set above = is_state('sun.sun', 'above_horizon') %}
          {% set rising = state_attr('sun.sun', 'rising') %}
          {% if above and rising %}
            {% set h = nn %}
            {% set x = prev_nr %}
            {% set k = 1 %}
          {% elif above and not rising %}
            {% set h = prev_nn %}
            {% set x = ns %}
            {% set k = 1 %}
          {% elif (not above) and rising %}
            {% set h = prev_nm %}
            {% set x = nr %}
            {% set k = -1 %}
          {% else %}
            {% set h = nm %}
            {% set x = prev_ns %}
            {% set k = -1 %}
          {% endif %}
          {% if (h - x) != 0 %}
            {{ (k * (1 - (((t - h) / (h - x)) ** 2))) | float(0) }}
          {% else %}
            0
          {% endif %}
        {% else %}
          0
        {% endif %}
      target_brightness: >
        {% set p = sun_position | float(0) %}
        {% set b_min = [b_night | float(1), b_day | float(100)] | min %}
        {% set b_max = [b_night | float(1), b_day | float(100)] | max %}
        {% set dark_s = 900 %}
        {% set light_s = 3600 %}
        {% set above = is_state('sun.sun', 'above_horizon') %}
        {% set rising = state_attr('sun.sun', 'rising') %}
        {% if above and rising %}
          {% set event = 'sunrise' %}
          {% set ts_event = (nr_ts | float(0)) - 86400 %}
        {% elif above and not rising %}
          {% set event = 'sunset' %}
          {% set ts_event = ns_ts | float(0) %}
        {% elif (not above) and rising %}
          {% set event = 'sunrise' %}
          {% set ts_event = nr_ts | float(0) %}
        {% else %}
          {% set event = 'sunset' %}
          {% set ts_event = (ns_ts | float(0)) - 86400 %}
        {% endif %}
        {% if event == 'sunrise' %}
          {% set x1 = ts_event - dark_s %}
          {% set x2 = ts_event + light_s %}
          {% set y1 = b_min %}
          {% set y2 = b_max %}
        {% else %}
          {% set x1 = ts_event - light_s %}
          {% set x2 = ts_event + dark_s %}
          {% set y1 = b_max %}
          {% set y2 = b_min %}
        {% endif %}
        {% if x2 != x1 %}
          {% set b = y1 + ((n_shifted_ts | float(0)) - x1) * (y2 - y1) / (x2 - x1) %}
          {{ [b_min, [b, b_max] | min] | max | round(0) | int }}
        {% else %}
          {{ b_min | round(0) | int }}
        {% endif %}
      target_kelvin: >
        {% set p = sun_position | float(0) %}
        {% set k_min = [k_night | float(2200), k_day | float(5000)] | min %}
        {% set k_max = [k_night | float(2200), k_day | float(5000)] | max %}
        {% if p > 0 %}
          {{ ((k_max - k_min) * p + k_min) | round(0) | int }}
        {% else %}
          {{ k_min | round(0) | int }}
        {% endif %}

  - event: adaptive_lighting_value
    event_data:
      instance_id: "{{ this.entity_id }}"
      kelvin: "{{ target_kelvin }}"
      brightness_pct: "{{ target_brightness }}"
      ratio: "{{ sun_position | float(0) }}"
      sun_position: "{{ sun_position | float(0) }}"
      sun_offset_min: "{{ sun_offset_min | int(0) }}"
      trigger_id: "{{ trigger.id }}"
      lights: "{{ target_lights_to_update }}"

  - repeat:
      for_each: "{{ target_lights_to_update }}"
      sequence:
        - variables:
            modes: "{{ state_attr(repeat.item, 'supported_color_modes') or [] }}"
            min_k: "{{ state_attr(repeat.item, 'min_color_temp_kelvin') | float(0) }}"
            max_k: "{{ state_attr(repeat.item, 'max_color_temp_kelvin') | float(0) }}"
            has_brightness_attr: "{{ state_attr(repeat.item, 'brightness') is not none }}"
            supports_ct: >
              {{ 'color_temp' in modes
                 or (min_k > 0 and max_k > 0)
                 or (state_attr(repeat.item, 'color_temp_kelvin') is not none)
                 or (state_attr(repeat.item, 'color_temp') is not none) }}
            # In Z2M/groups, supported_color_modes can be empty or partial.
            # Default to brightness-capable unless explicitly onoff-only.
            supports_brightness: >
              {{ has_brightness_attr
                 or (modes | count == 0)
                 or not ((modes | count == 1) and (modes[0] == 'onoff')) }}
            clamped_kelvin: >
              {% if min_k > 0 and max_k > 0 %}
                {{ [min_k, [target_kelvin | float(0), max_k] | min] | max | round(0) | int }}
              {% else %}
                {{ target_kelvin | int(0) }}
              {% endif %}
        - choose:
            - conditions:
                - condition: template
                  value_template: "{{ supports_brightness and supports_ct }}"
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: "{{ repeat.item }}"
                  data:
                    brightness_pct: "{{ target_brightness }}"
                    color_temp_kelvin: "{{ clamped_kelvin }}"
                    transition: "{{ fade_s | int(2) }}"
            - conditions:
                - condition: template
                  value_template: "{{ supports_brightness and not supports_ct }}"
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: "{{ repeat.item }}"
                  data:
                    brightness_pct: "{{ target_brightness }}"
                    transition: "{{ fade_s | int(2) }}"
            - conditions:
                - condition: template
                  value_template: "{{ (not supports_brightness) and supports_ct }}"
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: "{{ repeat.item }}"
                  data:
                    color_temp_kelvin: "{{ clamped_kelvin }}"
                    transition: "{{ fade_s | int(2) }}"
          default:
            - service: light.turn_on
              target:
                entity_id: "{{ repeat.item }}"
              data:
                transition: "{{ fade_s | int(2) }}"
