blueprint:
  name: Simple Adaptive Room Lighting
  description: >
    Lightweight adaptive lighting blueprint.
    It updates brightness and white temperature from sun elevation, for the lights
    currently on in a room.
    Manual control is handled with a dedicated input_boolean: when off, adaptive
    updates are paused; when on, updates resume.
  domain: automation
  input:
    target_lights:
      name: Target lights
      description: Lights controlled by this automation instance.
      selector:
        entity:
          domain: light
          multiple: true

    auto_mode_boolean:
      name: Adaptive auto mode
      description: Optional input_boolean controlling adaptive mode (on = adaptive active, off = manual mode).
      default: ""
      selector:
        entity:
          domain: input_boolean

    update_interval_min:
      name: Update interval (minutes)
      description: Re-apply adaptive values every N minutes.
      default: 2
      selector:
        number:
          min: 1
          max: 30
          step: 1
          mode: slider
          unit_of_measurement: min

    transition_sec:
      name: Transition duration (seconds)
      default: 2
      selector:
        number:
          min: 0
          max: 120
          step: 1
          mode: slider
          unit_of_measurement: s

    brightness_night:
      name: Brightness at night (%)
      default: 10
      selector:
        number:
          min: 1
          max: 100
          step: 1
          mode: slider
          unit_of_measurement: "%"

    brightness_day:
      name: Brightness at day peak (%)
      default: 85
      selector:
        number:
          min: 1
          max: 100
          step: 1
          mode: slider
          unit_of_measurement: "%"

    kelvin_night:
      name: Kelvin at night
      default: 2200
      selector:
        number:
          min: 1800
          max: 5000
          step: 50
          mode: slider
          unit_of_measurement: K

    kelvin_day:
      name: Kelvin at day peak
      default: 5000
      selector:
        number:
          min: 2200
          max: 9000
          step: 50
          mode: slider
          unit_of_measurement: K

    day_span_adjustment_min:
      name: Day span adjustment (minutes)
      description: Extend the adaptive day beyond sun events (+) or shorten it (-). Example: -60 starts 60 min later and ends 60 min earlier.
      default: 0
      selector:
        number:
          min: -120
          max: 120
          step: 5
          mode: slider
          unit_of_measurement: min


mode: restart

variables:
  room_lights: !input target_lights
  auto_mode_entity: !input auto_mode_boolean
  interval_min: !input update_interval_min
  fade_s: !input transition_sec
  b_night: !input brightness_night
  b_day: !input brightness_day
  k_night: !input kelvin_night
  k_day: !input kelvin_day
  day_span_adjustment_min: !input day_span_adjustment_min
  light_entities: >
    {% if room_lights is string %}
      {{ [room_lights] }}
    {% else %}
      {{ room_lights | list }}
    {% endif %}

trigger:
  - platform: time_pattern
    minutes: "/1"
    id: tick

  - platform: state
    entity_id: !input target_lights
    to: "on"
    id: light_on

  - platform: sun
    event: sunrise
    id: sun_event

  - platform: sun
    event: sunset
    id: sun_event

condition:
  - condition: template
    value_template: >
      {{ auto_mode_entity in ['', none] or is_state(auto_mode_entity, 'on') }}

  - condition: template
    value_template: >
      {{ trigger.id != 'tick' or (now().minute % (interval_min | int(2)) == 0) }}

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'light_on' }}"
        sequence:
          - delay:
              milliseconds: 800

  - variables:
      on_lights: >
        {{ expand(light_entities)
           | selectattr('state', 'eq', 'on')
           | map(attribute='entity_id')
           | list }}
      target_lights_to_update: >
        {% if trigger.id == 'light_on' and trigger.entity_id in light_entities %}
          {{ ([trigger.entity_id] + on_lights) | unique | list }}
        {% else %}
          {{ on_lights }}
        {% endif %}

  - condition: template
    value_template: "{{ target_lights_to_update | count > 0 }}"

  - variables:
      n_ts: "{{ as_timestamp(now()) }}"
      nr_ts: "{{ as_timestamp(state_attr('sun.sun', 'next_rising')) }}"
      ns_ts: "{{ as_timestamp(state_attr('sun.sun', 'next_setting')) }}"
      day_span_s: "{{ day_span_adjustment_min | float(0) * 60 }}"
      # Adaptive day span:
      # +offset => sunrise earlier + sunset later (longer day)
      # -offset => sunrise later + sunset earlier (shorter day)
      # sun_position in [-1, 1]: 0 at adjusted sunrise/sunset, +1 at adjusted noon, -1 at adjusted midnight.
      sun_position: >
        {% if nr_ts and ns_ts %}
          {% set t = n_ts | float(0) %}
          {% set nr = nr_ts | float(0) %}
          {% set ns = ns_ts | float(0) %}
          {% set o = day_span_s | float(0) %}
          {% set sr_prev = (nr - 86400) - o %}
          {% set sr_next = nr - o %}
          {% set ss_prev = (ns - 86400) + o %}
          {% set ss_next = ns + o %}
          {% if t >= sr_prev and t < ss_prev %}
            {% set day_start = sr_prev %}
            {% set day_end = ss_prev %}
            {% if (day_end - day_start) != 0 %}
              {% set d = (t - day_start) / (day_end - day_start) %}
              {% set d = [0, [d, 1] | min] | max %}
              {{ (1 - ((2 * d - 1) ** 2)) | float(0) }}
            {% else %}
              0
            {% endif %}
          {% elif t >= sr_next and t < ss_next %}
            {% set day_start = sr_next %}
            {% set day_end = ss_next %}
            {% if (day_end - day_start) != 0 %}
              {% set d = (t - day_start) / (day_end - day_start) %}
              {% set d = [0, [d, 1] | min] | max %}
              {{ (1 - ((2 * d - 1) ** 2)) | float(0) }}
            {% else %}
              0
            {% endif %}
          {% else %}
            {% if t >= ss_prev and t < sr_next %}
              {% set night_start = ss_prev %}
              {% set night_end = sr_next %}
            {% elif t < sr_prev %}
              {% set night_start = ss_prev - 86400 %}
              {% set night_end = sr_prev %}
            {% else %}
              {% set night_start = ss_next %}
              {% set night_end = sr_next + 86400 %}
            {% endif %}
            {% if (night_end - night_start) != 0 %}
              {% set n = (t - night_start) / (night_end - night_start) %}
              {% set n = [0, [n, 1] | min] | max %}
              {{ (-(1 - ((2 * n - 1) ** 2))) | float(0) }}
            {% else %}
              0
            {% endif %}
          {% endif %}
        {% else %}
          0
        {% endif %}
      target_brightness: >
        {% set p = sun_position | float(0) %}
        {% set b_min = [b_night | float(1), b_day | float(100)] | min %}
        {% set b_max = [b_night | float(1), b_day | float(100)] | max %}
        {% set dark_s = 900 %}
        {% set light_s = 3600 %}
        {% set o = day_span_s | float(0) %}
        {% set t = n_ts | float(0) %}
        {% set sr_prev = ((nr_ts | float(0)) - 86400) - o %}
        {% set sr_next = (nr_ts | float(0)) - o %}
        {% set ss_prev = ((ns_ts | float(0)) - 86400) + o %}
        {% set ss_next = (ns_ts | float(0)) + o %}
        {% if t >= sr_prev and t < ss_prev %}
          {% set above = true %}
          {% set day_sr = sr_prev %}
          {% set day_ss = ss_prev %}
        {% elif t >= sr_next and t < ss_next %}
          {% set above = true %}
          {% set day_sr = sr_next %}
          {% set day_ss = ss_next %}
        {% else %}
          {% set above = false %}
        {% endif %}
        {% if above %}
          {% set day_noon = (day_sr + day_ss) / 2 %}
          {% set rising = t < day_noon %}
        {% else %}
          {% set rising = false %}
        {% endif %}
        {% if above and rising %}
          {% set event = 'sunrise' %}
          {% set ts_event = day_sr %}
        {% elif above and not rising %}
          {% set event = 'sunset' %}
          {% set ts_event = day_ss %}
        {% else %}
          {% set event = 'sunrise' %}
          {% set ts_event = sr_next %}
        {% endif %}
        {% if event == 'sunrise' %}
          {% set x1 = ts_event - dark_s %}
          {% set x2 = ts_event + light_s %}
          {% set y1 = b_min %}
          {% set y2 = b_max %}
        {% else %}
          {% set x1 = ts_event - light_s %}
          {% set x2 = ts_event + dark_s %}
          {% set y1 = b_max %}
          {% set y2 = b_min %}
        {% endif %}
        {% if x2 != x1 %}
          {% set b = y1 + ((n_ts | float(0)) - x1) * (y2 - y1) / (x2 - x1) %}
          {{ [b_min, [b, b_max] | min] | max | round(0) | int }}
        {% else %}
          {{ b_min | round(0) | int }}
        {% endif %}
      target_kelvin: >
        {% set p = sun_position | float(0) %}
        {% set k_min = [k_night | float(2200), k_day | float(5000)] | min %}
        {% set k_max = [k_night | float(2200), k_day | float(5000)] | max %}
        {% if p > 0 %}
          {{ ((k_max - k_min) * p + k_min) | round(0) | int }}
        {% else %}
          {{ k_min | round(0) | int }}
        {% endif %}

  - event: adaptive_lighting_value
    event_data:
      instance_id: "{{ this.entity_id }}"
      kelvin: "{{ target_kelvin }}"
      brightness_pct: "{{ target_brightness }}"
      ratio: "{{ sun_position | float(0) }}"
      sun_position: "{{ sun_position | float(0) }}"
      day_span_adjustment_min: "{{ day_span_adjustment_min | int(0) }}"
      trigger_id: "{{ trigger.id }}"
      lights: "{{ target_lights_to_update }}"

  - repeat:
      for_each: "{{ target_lights_to_update }}"
      sequence:
        - variables:
            modes: "{{ state_attr(repeat.item, 'supported_color_modes') or [] }}"
            min_k: "{{ state_attr(repeat.item, 'min_color_temp_kelvin') | float(0) }}"
            max_k: "{{ state_attr(repeat.item, 'max_color_temp_kelvin') | float(0) }}"
            has_brightness_attr: "{{ state_attr(repeat.item, 'brightness') is not none }}"
            supports_ct: >
              {{ 'color_temp' in modes
                 or (min_k > 0 and max_k > 0)
                 or (state_attr(repeat.item, 'color_temp_kelvin') is not none)
                 or (state_attr(repeat.item, 'color_temp') is not none) }}
            # In Z2M/groups, supported_color_modes can be empty or partial.
            # Default to brightness-capable unless explicitly onoff-only.
            supports_brightness: >
              {{ has_brightness_attr
                 or (modes | count == 0)
                 or not ((modes | count == 1) and (modes[0] == 'onoff')) }}
            clamped_kelvin: >
              {% if min_k > 0 and max_k > 0 %}
                {{ [min_k, [target_kelvin | float(0), max_k] | min] | max | round(0) | int }}
              {% else %}
                {{ target_kelvin | int(0) }}
              {% endif %}
        - choose:
            - conditions:
                - condition: template
                  value_template: "{{ supports_brightness and supports_ct }}"
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: "{{ repeat.item }}"
                  data:
                    brightness_pct: "{{ target_brightness }}"
                    color_temp_kelvin: "{{ clamped_kelvin }}"
                    transition: "{{ fade_s | int(2) }}"
            - conditions:
                - condition: template
                  value_template: "{{ supports_brightness and not supports_ct }}"
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: "{{ repeat.item }}"
                  data:
                    brightness_pct: "{{ target_brightness }}"
                    transition: "{{ fade_s | int(2) }}"
            - conditions:
                - condition: template
                  value_template: "{{ (not supports_brightness) and supports_ct }}"
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: "{{ repeat.item }}"
                  data:
                    color_temp_kelvin: "{{ clamped_kelvin }}"
                    transition: "{{ fade_s | int(2) }}"
          default:
            - service: light.turn_on
              target:
                entity_id: "{{ repeat.item }}"
              data:
                transition: "{{ fade_s | int(2) }}"
