blueprint:
  name: Simple Adaptive Room Lighting
  description: >
    Lightweight adaptive lighting blueprint.
    It updates brightness and white temperature from sun elevation, for the lights
    currently on in a room.
    Manual control is handled with a dedicated input_boolean: when off, adaptive
    updates are paused; when on, updates resume.
  domain: automation
  input:
    target_lights:
      name: Target lights
      description: Lights controlled by this automation instance.
      selector:
        entity:
          domain: light
          multiple: true

    auto_mode_boolean:
      name: Adaptive auto mode
      description: Optional input_boolean controlling adaptive mode (on = adaptive active, off = manual mode).
      default: ""
      selector:
        entity:
          domain: input_boolean

    update_interval_min:
      name: Update interval (minutes)
      description: Re-apply adaptive values every N minutes.
      default: 2
      selector:
        number:
          min: 1
          max: 30
          step: 1
          mode: slider
          unit_of_measurement: min

    transition_sec:
      name: Transition duration (seconds)
      default: 2
      selector:
        number:
          min: 0
          max: 120
          step: 1
          mode: slider
          unit_of_measurement: s

    brightness_night:
      name: Brightness at night (%)
      default: 10
      selector:
        number:
          min: 1
          max: 100
          step: 1
          mode: slider
          unit_of_measurement: "%"

    brightness_day:
      name: Brightness at day peak (%)
      default: 85
      selector:
        number:
          min: 1
          max: 100
          step: 1
          mode: slider
          unit_of_measurement: "%"

    kelvin_night:
      name: Kelvin at night
      default: 2200
      selector:
        number:
          min: 1800
          max: 5000
          step: 50
          mode: slider
          unit_of_measurement: K

    kelvin_day:
      name: Kelvin at day peak
      default: 5000
      selector:
        number:
          min: 2200
          max: 9000
          step: 50
          mode: slider
          unit_of_measurement: K

    peak_plateau_min:
      name: Peak plateau half-width (minutes)
      description: Keep max values from (solar peak - N min) to (solar peak + N min).
      default: 60
      selector:
        number:
          min: 0
          max: 240
          step: 5
          mode: slider
          unit_of_measurement: min

mode: single

variables:
  room_lights: !input target_lights
  auto_mode_entity: !input auto_mode_boolean
  interval_min: !input update_interval_min
  fade_s: !input transition_sec
  b_night: !input brightness_night
  b_day: !input brightness_day
  k_night: !input kelvin_night
  k_day: !input kelvin_day
  plateau_min: !input peak_plateau_min
  light_entities: >
    {% if room_lights is string %}
      {{ [room_lights] }}
    {% else %}
      {{ room_lights | list }}
    {% endif %}

trigger:
  - platform: time_pattern
    minutes: "/1"
    id: tick

  - platform: state
    entity_id: !input target_lights
    to: "on"
    id: light_on

  - platform: sun
    event: sunrise
    id: sun_event

  - platform: sun
    event: sunset
    id: sun_event

condition:
  - condition: template
    value_template: >
      {{ auto_mode_entity in ['', none] or is_state(auto_mode_entity, 'on') }}

  - condition: template
    value_template: >
      {{ trigger.id != 'tick' or (now().minute % (interval_min | int(2)) == 0) }}

action:
  - variables:
      on_lights: >
        {{ expand(light_entities)
           | selectattr('state', 'eq', 'on')
           | map(attribute='entity_id')
           | list }}

  - condition: template
    value_template: "{{ on_lights | count > 0 }}"

  - variables:
      n: "{{ now() }}"
      nr: "{{ as_datetime(state_attr('sun.sun', 'next_rising')) }}"
      ns: "{{ as_datetime(state_attr('sun.sun', 'next_setting')) }}"
      # Piecewise curve sunrise->solar_peak->sunset with a flat max plateau around solar peak.
      ratio: >
        {% if nr and ns and (nr > ns) %}
          {% set sunrise = nr - timedelta(days=1) %}
          {% set sunset = ns %}
          {% set t = as_timestamp(n) %}
          {% set s = as_timestamp(sunrise) %}
          {% set e = as_timestamp(sunset) %}
          {% set p = (s + e) / 2 %}
          {% set w = (plateau_min | int(60)) * 60 %}
          {% set ps = p - w %}
          {% set pe = p + w %}
          {% if t <= s or t >= e %}
            0
          {% elif t < ps and ps > s %}
            {{ (t - s) / (ps - s) }}
          {% elif t <= pe %}
            1
          {% elif e > pe %}
            {{ (e - t) / (e - pe) }}
          {% else %}
            0
          {% endif %}
        {% else %}
          0
        {% endif %}
      target_brightness: >
        {{ (b_night | float(10) + (b_day | float(85) - b_night | float(10)) * (ratio | float(0)))
           | round(0) | int }}
      target_kelvin: >
        {{ (k_night | float(2200) + (k_day | float(5000) - k_night | float(2200)) * (ratio | float(0)))
           | round(0) | int }}

  - service: light.turn_on
    target:
      entity_id: "{{ on_lights }}"
    data:
      brightness_pct: "{{ target_brightness }}"
      kelvin: "{{ target_kelvin }}"
      transition: "{{ fade_s | int(2) }}"
