blueprint:
  name: Simple Adaptive Room Lighting
  description: >
    Lightweight adaptive lighting blueprint.
    It updates brightness and white temperature from sun elevation, for the lights
    currently on in a room.
    Optional night mode can be linked to an external input_boolean to force a fixed
    brightness and color temperature while active.
    Manual control is handled with a dedicated input_boolean: when off, adaptive
    updates are paused; when on, updates resume. Night mode override has priority.
  domain: automation
  homeassistant:
    min_version: 2024.6.0
  input:
    target_lights:
      name: Target lights
      description: Lights controlled by this automation instance.
      selector:
        entity:
          domain: light
          multiple: true

    adaptive_settings:
      name: Adaptive settings
      icon: mdi:tune-vertical
      input:
        update_interval_min:
          name: Update interval (minutes)
          description: Re-apply adaptive values every N minutes.
          default: 2
          selector:
            number:
              min: 1
              max: 30
              step: 1
              mode: slider
              unit_of_measurement: min

        transition_sec:
          name: Transition duration (seconds)
          default: 10
          selector:
            number:
              min: 0
              max: 120
              step: 1
              mode: slider
              unit_of_measurement: s

        brightness_night:
          name: Brightness at night (%)
          default: 30
          selector:
            number:
              min: 1
              max: 100
              step: 1
              mode: slider
              unit_of_measurement: "%"

        brightness_day:
          name: Brightness at day peak (%)
          default: 100
          selector:
            number:
              min: 1
              max: 100
              step: 1
              mode: slider
              unit_of_measurement: "%"

        kelvin_night:
          name: Kelvin at night
          default: 2700
          selector:
            number:
              min: 1800
              max: 5000
              step: 50
              mode: slider
              unit_of_measurement: K

        kelvin_day:
          name: Kelvin at day peak
          default: 5500
          selector:
            number:
              min: 2200
              max: 9000
              step: 50
              mode: slider
              unit_of_measurement: K

        day_span_adjustment_min:
          name: Day span adjustment (minutes)
          description: "Extend the adaptive day beyond sun events (+) or shorten it (-). Example: -60 starts 60 min later and ends 60 min earlier."
          default: 30
          selector:
            number:
              min: -120
              max: 120
              step: 5
              mode: slider
              unit_of_measurement: min

    auto_mode_section:
      name: Optional auto mode input
      icon: mdi:toggle-switch
      collapsed: true
      input:
        enable_auto_mode:
          name: Enable auto mode input_boolean
          description: Tick to enable manual pause/resume via an input_boolean.
          default: false
          selector:
            boolean:

        auto_mode_boolean:
          name: Adaptive auto mode entity
          description: input_boolean controlling adaptive mode (on = adaptive active, off = manual mode).
          default: ""
          selector:
            entity:
              domain: input_boolean

    night_mode_section:
      name: Optional night mode override
      icon: mdi:weather-night
      collapsed: true
      input:
        enable_night_mode:
          name: Enable night mode override
          description: Tick to force fixed night values when the selected input_boolean is on.
          default: false
          selector:
            boolean:

        night_mode_boolean:
          name: Night mode override entity
          description: input_boolean forcing fixed brightness and color temperature while on.
          default: ""
          selector:
            entity:
              domain: input_boolean

        night_mode_brightness:
          name: Night mode fixed brightness (%)
          default: 5
          selector:
            number:
              min: 1
              max: 50
              step: 1
              mode: slider
              unit_of_measurement: "%"

        night_mode_kelvin:
          name: Night mode fixed kelvin
          default: 2200
          selector:
            number:
              min: 2000
              max: 4000
              step: 50
              mode: slider
              unit_of_measurement: K


mode: restart

variables:
  room_lights: !input target_lights
  auto_mode_enabled: !input enable_auto_mode
  auto_mode_input_entity: !input auto_mode_boolean
  night_mode_enabled: !input enable_night_mode
  night_mode_input_entity: !input night_mode_boolean
  auto_mode_entity: >
    {% if auto_mode_enabled %}
      {{ auto_mode_input_entity }}
    {% else %}
      {{ "" }}
    {% endif %}
  night_mode_entity: >
    {% if night_mode_enabled %}
      {{ night_mode_input_entity }}
    {% else %}
      {{ "" }}
    {% endif %}
  night_mode_brightness: !input night_mode_brightness
  night_mode_kelvin: !input night_mode_kelvin
  interval_min: !input update_interval_min
  fade_s: !input transition_sec
  b_night: !input brightness_night
  b_day: !input brightness_day
  k_night: !input kelvin_night
  k_day: !input kelvin_day
  day_span_adjustment_min: !input day_span_adjustment_min
  light_entities: >
    {% if room_lights is string %}
      {{ [room_lights] }}
    {% else %}
      {{ room_lights | list }}
    {% endif %}

trigger:
  - platform: time_pattern
    minutes: "/1"
    id: tick

  - platform: state
    entity_id: !input target_lights
    to: "on"
    id: light_on

  - platform: sun
    event: sunrise
    id: sun_event

  - platform: sun
    event: sunset
    id: sun_event

condition:
  - condition: template
    value_template: >
      {% set night_override = (night_mode_entity not in ['', none]) and is_state(night_mode_entity, 'on') %}
      {{ night_override or auto_mode_entity in ['', none] or is_state(auto_mode_entity, 'on') }}

  - condition: template
    value_template: >
      {{ trigger.id != 'tick' or (now().minute % (interval_min | int(2)) == 0) }}

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'light_on' }}"
        sequence:
          - delay:
              milliseconds: 800

  - variables:
      on_lights: >
        {{ expand(light_entities)
           | selectattr('state', 'eq', 'on')
           | map(attribute='entity_id')
           | list }}
      target_lights_to_update: >
        {% if trigger.id == 'light_on' and trigger.entity_id in light_entities %}
          {{ ([trigger.entity_id] + on_lights) | unique | list }}
        {% else %}
          {{ on_lights }}
        {% endif %}
      night_override: >
        {{ (night_mode_entity not in ['', none]) and is_state(night_mode_entity, 'on') }}

  - condition: template
    value_template: "{{ target_lights_to_update | count > 0 }}"

  - variables:
      n_ts: "{{ as_timestamp(now()) }}"
      nr_ts: "{{ as_timestamp(state_attr('sun.sun', 'next_rising')) }}"
      ns_ts: "{{ as_timestamp(state_attr('sun.sun', 'next_setting')) }}"
      day_span_s: "{{ day_span_adjustment_min | float(0) * 60 }}"
      # Adaptive day span:
      # +offset => sunrise earlier + sunset later (longer day)
      # -offset => sunrise later + sunset earlier (shorter day)
      # sun_position in [-1, 1]: 0 at adjusted sunrise/sunset, +1 at adjusted noon, -1 at adjusted midnight.
      sun_position: >
        {% if nr_ts and ns_ts %}
          {% set t = n_ts | float(0) %}
          {% set nr = nr_ts | float(0) %}
          {% set ns = ns_ts | float(0) %}
          {% set o = day_span_s | float(0) %}
          {% set sr0 = (nr - (86400 if nr > ns else 0)) - o %}
          {% set ss0 = ns + o %}
          {% set sr_prev = sr0 - 86400 %}
          {% set ss_prev = ss0 - 86400 %}
          {% if t >= sr0 and t < ss0 %}
            {% set day_start = sr0 %}
            {% set day_end = ss0 %}
            {% set d = (t - day_start) / (day_end - day_start) %}
            {% set d = [0, [d, 1] | min] | max %}
            {{ (1 - ((2 * d - 1) ** 2)) | float(0) }}
          {% elif t >= sr_prev and t < ss_prev %}
            {% set day_start = sr_prev %}
            {% set day_end = ss_prev %}
            {% set d = (t - day_start) / (day_end - day_start) %}
            {% set d = [0, [d, 1] | min] | max %}
            {{ (1 - ((2 * d - 1) ** 2)) | float(0) }}
          {% elif t < sr0 %}
            {% set night_start = ss_prev %}
            {% set night_end = sr0 %}
            {% set n = (t - night_start) / (night_end - night_start) %}
            {% set n = [0, [n, 1] | min] | max %}
            {{ (-(1 - ((2 * n - 1) ** 2))) | float(0) }}
          {% else %}
            {% set night_start = ss0 %}
            {% set night_end = sr0 + 86400 %}
            {% set n = (t - night_start) / (night_end - night_start) %}
            {% set n = [0, [n, 1] | min] | max %}
            {{ (-(1 - ((2 * n - 1) ** 2))) | float(0) }}
          {% endif %}
        {% else %}
          0
        {% endif %}
      target_brightness: >
        {% if night_override %}
          {{ night_mode_brightness | int(5) }}
        {% else %}
          {% set b_min = [b_night | float(1), b_day | float(100)] | min %}
          {% set b_max = [b_night | float(1), b_day | float(100)] | max %}
          {% set o = day_span_s | float(0) %}
          {% set t = n_ts | float(0) %}
          {% set nr = nr_ts | float(0) %}
          {% set ns = ns_ts | float(0) %}
          {% set sr0 = (nr - (86400 if nr > ns else 0)) - o %}
          {% set ss0 = ns + o %}
          {% set sr_prev = sr0 - 86400 %}
          {% set ss_prev = ss0 - 86400 %}
          {% set plateau_target_s = 25200 %}
          {% set edge_s = 900 %}
          {% if t >= sr0 and t < ss0 %}
            {% set day_sr = sr0 %}
            {% set day_ss = ss0 %}
          {% elif t >= sr_prev and t < ss_prev %}
            {% set day_sr = sr_prev %}
            {% set day_ss = ss_prev %}
          {% else %}
            {% set day_sr = none %}
            {% set day_ss = none %}
          {% endif %}
          {% if day_sr is none %}
            {{ b_min | round(0) | int }}
          {% else %}
            {% set day_len_s = day_ss - day_sr %}
            {% set ramp_s = [0, (day_len_s - plateau_target_s) / 2] | max %}
            {% set up_start = day_sr - edge_s %}
            {% set up_end = day_sr + ramp_s %}
            {% set down_start = day_ss - ramp_s %}
            {% set down_end = day_ss + edge_s %}
            {% if t < up_start %}
              {% set b = b_min %}
            {% elif t <= up_end %}
              {% set u = (t - up_start) / (up_end - up_start) %}
              {% set u = [0, [u, 1] | min] | max %}
              {% set z = (2 * u) - 1 %}
              {% set az = 1.4 * z %}
              {% set z2 = az * az %}
              {% set tnh = (az * (27 + z2)) / (27 + (9 * z2)) %}
              {% set s = (tnh + 1) / 2 %}
              {% set b = b_min + (b_max - b_min) * s %}
            {% elif t < down_start %}
              {% set b = b_max %}
            {% elif t <= down_end %}
              {% set u = (t - down_start) / (down_end - down_start) %}
              {% set u = [0, [u, 1] | min] | max %}
              {% set z = (2 * u) - 1 %}
              {% set az = 1.4 * z %}
              {% set z2 = az * az %}
              {% set tnh = (az * (27 + z2)) / (27 + (9 * z2)) %}
              {% set s = (tnh + 1) / 2 %}
              {% set b = b_max - (b_max - b_min) * s %}
            {% else %}
              {% set b = b_min %}
            {% endif %}
            {{ [b_min, [b, b_max] | min] | max | round(0) | int }}
          {% endif %}
        {% endif %}
      target_kelvin: >
        {% if night_override %}
          {{ night_mode_kelvin | int(2200) }}
        {% else %}
          {% set p = sun_position | float(0) %}
          {% set k_min = [k_night | float(2200), k_day | float(5000)] | min %}
          {% set k_max = [k_night | float(2200), k_day | float(5000)] | max %}
          {% if p > 0 %}
            {{ ((k_max - k_min) * p + k_min) | round(0) | int }}
          {% else %}
            {{ k_min | round(0) | int }}
          {% endif %}
        {% endif %}

  - event: adaptive_lighting_value
    event_data:
      instance_id: "{{ this.entity_id }}"
      kelvin: "{{ target_kelvin }}"
      brightness_pct: "{{ target_brightness }}"
      ratio: "{{ sun_position | float(0) }}"
      sun_position: "{{ sun_position | float(0) }}"
      day_span_adjustment_min: "{{ day_span_adjustment_min | int(0) }}"
      night_override: "{{ night_override }}"
      trigger_id: "{{ trigger.id }}"
      lights: "{{ target_lights_to_update }}"

  - repeat:
      for_each: "{{ target_lights_to_update }}"
      sequence:
        - variables:
            modes: "{{ state_attr(repeat.item, 'supported_color_modes') or [] }}"
            min_k: "{{ state_attr(repeat.item, 'min_color_temp_kelvin') | float(0) }}"
            max_k: "{{ state_attr(repeat.item, 'max_color_temp_kelvin') | float(0) }}"
            has_brightness_attr: "{{ state_attr(repeat.item, 'brightness') is not none }}"
            supports_ct: >
              {{ 'color_temp' in modes
                 or (min_k > 0 and max_k > 0)
                 or (state_attr(repeat.item, 'color_temp_kelvin') is not none)
                 or (state_attr(repeat.item, 'color_temp') is not none) }}
            # In Z2M/groups, supported_color_modes can be empty or partial.
            # Default to brightness-capable unless explicitly onoff-only.
            supports_brightness: >
              {{ has_brightness_attr
                 or (modes | count == 0)
                 or not ((modes | count == 1) and (modes[0] == 'onoff')) }}
            clamped_kelvin: >
              {% if min_k > 0 and max_k > 0 %}
                {{ [min_k, [target_kelvin | float(0), max_k] | min] | max | round(0) | int }}
              {% else %}
                {{ target_kelvin | int(0) }}
              {% endif %}
        - choose:
            - conditions:
                - condition: template
                  value_template: "{{ supports_brightness and supports_ct }}"
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: "{{ repeat.item }}"
                  data:
                    brightness_pct: "{{ target_brightness }}"
                    color_temp_kelvin: "{{ clamped_kelvin }}"
                    transition: "{{ fade_s | int(2) }}"
            - conditions:
                - condition: template
                  value_template: "{{ supports_brightness and not supports_ct }}"
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: "{{ repeat.item }}"
                  data:
                    brightness_pct: "{{ target_brightness }}"
                    transition: "{{ fade_s | int(2) }}"
            - conditions:
                - condition: template
                  value_template: "{{ (not supports_brightness) and supports_ct }}"
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: "{{ repeat.item }}"
                  data:
                    color_temp_kelvin: "{{ clamped_kelvin }}"
                    transition: "{{ fade_s | int(2) }}"
          default:
            - service: light.turn_on
              target:
                entity_id: "{{ repeat.item }}"
              data:
                transition: "{{ fade_s | int(2) }}"
