blueprint:
  name: "[[blueprint.name]] ([[blueprint.version]])"
  description: |-
    [[blueprint.description]]

    [[blueprint.version.line]]
  domain: automation
  homeassistant:
    min_version: 2024.6.0
  input:
    target_lights:
      name: [[input.target_lights.name]]
      description: [[input.target_lights.description]]
      selector:
        entity:
          domain: light
          multiple: true

    adaptive_settings:
      name: [[input.adaptive_settings.name]]
      icon: mdi:tune-vertical
      input:
        brightness_night:
          name: [[input.brightness_night.name]]
          description: [[input.brightness_night.description]]
          default: 30
          selector:
            number:
              min: 1
              max: 100
              step: 1
              mode: slider
              unit_of_measurement: "%"

        brightness_day:
          name: [[input.brightness_day.name]]
          description: [[input.brightness_day.description]]
          default: 100
          selector:
            number:
              min: 1
              max: 100
              step: 1
              mode: slider
              unit_of_measurement: "%"

        kelvin_night:
          name: [[input.kelvin_night.name]]
          description: [[input.kelvin_night.description]]
          default: 2700
          selector:
            number:
              min: 1800
              max: 5000
              step: 50
              mode: slider
              unit_of_measurement: K

        kelvin_day:
          name: [[input.kelvin_day.name]]
          description: [[input.kelvin_day.description]]
          default: 5500
          selector:
            number:
              min: 2200
              max: 9000
              step: 50
              mode: slider
              unit_of_measurement: K

    auto_mode_section:
      name: [[input.auto_mode_section.name]]
      icon: mdi:toggle-switch
      collapsed: true
      input:
        enable_auto_mode:
          name: [[input.enable_auto_mode.name]]
          description: [[input.enable_auto_mode.description]]
          default: false
          selector:
            boolean:

        auto_mode_boolean:
          name: [[input.auto_mode_boolean.name]]
          description: [[input.auto_mode_boolean.description]]
          default: ""
          selector:
            entity:
              filter:
                - domain: input_boolean
                - domain: binary_sensor

mode: restart

variables:
  blueprint_revision: "[[blueprint.version]]"
  auto_mode_enabled: !input enable_auto_mode
  auto_mode_input_entity: !input auto_mode_boolean
  b_night: !input brightness_night
  b_day: !input brightness_day
  k_night: !input kelvin_night
  k_day: !input kelvin_day
  light_entities: !input target_lights

trigger_variables:
  tick_light_entities: !input target_lights

trigger:
  - trigger: template
    alias: Tick while lights on
    # Run every 5 minutes, but only while at least one target light is on.
    value_template: >
      {{ (now().minute % 5 == 0)
         and (
           expand(tick_light_entities)
           | selectattr('state', 'eq', 'on')
           | list
           | count
         ) > 0 }}
    id: tick

  # Re-apply immediately when adaptive auto mode changes state.
  # Use state_changed event to support all transitions (on/off/unknown/unavailable).
  - trigger: event
    alias: Auto mode entity changed
    event_type: state_changed
    event_data:
      entity_id: !input auto_mode_boolean
    id: auto_mode_enabled

  # Re-apply immediately when automations are reloaded from HA UI/service.
  - trigger: event
    alias: Automations reloaded
    event_type: call_service
    event_data:
      domain: automation
      service: reload
    id: automations_reload_service

  - trigger: state
    alias: Light turned on
    entity_id: !input target_lights
    to: "on"
    id: light_on

  - trigger: sun
    alias: Sunrise
    event: sunrise
    id: sun_event

  - trigger: sun
    alias: Sunset
    event: sunset
    id: sun_event

condition:
  - condition: template
    value_template: >
      {{ trigger.id != 'auto_mode_enabled'
         or (
           auto_mode_enabled
           and auto_mode_input_entity not in ['', none]
           and trigger.event is defined
           and trigger.event.data is defined
           and trigger.event.data.new_state is not none
           and trigger.event.data.new_state.state == 'on'
           and (
             trigger.event.data.old_state is none
             or trigger.event.data.old_state.state != 'on'
           )
         ) }}

  - condition: template
    value_template: >
      {{ not auto_mode_enabled
         or auto_mode_input_entity in ['', none]
         or is_state(auto_mode_input_entity, 'on') }}

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'light_on' }}"
        sequence:
          - delay:
              milliseconds: 800

  - variables:
      on_lights: >
        {{ expand(light_entities)
           | selectattr('state', 'eq', 'on')
           | map(attribute='entity_id')
           | list }}
      target_lights_to_update: >
        {% if trigger.id == 'light_on' and trigger.entity_id in light_entities %}
          {{ ([trigger.entity_id] + on_lights) | unique | list }}
        {% else %}
          {{ on_lights }}
        {% endif %}

  - condition: template
    value_template: "{{ target_lights_to_update | count > 0 }}"

  - variables:
      now_ts: "{{ as_timestamp(now()) }}"
      next_rising_ts: "{{ as_timestamp(state_attr('sun.sun', 'next_rising')) }}"
      next_setting_ts: "{{ as_timestamp(state_attr('sun.sun', 'next_setting')) }}"
      day_offset_s: 2700
      sunrise_ts: >
        {% if next_rising_ts and next_setting_ts %}
          {% set nr = next_rising_ts | float(0) %}
          {% set ns = next_setting_ts | float(0) %}
          {{ (nr - (86400 if nr > ns else 0)) - (day_offset_s | float(1800)) }}
        {% else %}
          {{ none }}
        {% endif %}
      sunset_ts: >
        {% if next_rising_ts and next_setting_ts %}
          {{ (next_setting_ts | float(0)) + (day_offset_s | float(1800)) }}
        {% else %}
          {{ none }}
        {% endif %}
      previous_sunrise_ts: >
        {% if sunrise_ts is not none %}
          {{ (sunrise_ts | float(0)) - 86400 }}
        {% else %}
          {{ none }}
        {% endif %}
      previous_sunset_ts: >
        {% if sunset_ts is not none %}
          {{ (sunset_ts | float(0)) - 86400 }}
        {% else %}
          {{ none }}
        {% endif %}
      brightness_curve_gamma: 1.2
      # sun_position in [-1, 1]: 0 at adjusted sunrise/sunset, +1 at noon, -1 at midnight.
      sun_position: >
        {% if sunrise_ts is not none and sunset_ts is not none %}
          {% set t = now_ts | float(0) %}
          {% set sr0 = sunrise_ts | float(0) %}
          {% set ss0 = sunset_ts | float(0) %}
          {% set sr_prev = previous_sunrise_ts | float(0) %}
          {% set ss_prev = previous_sunset_ts | float(0) %}
          {% if t >= sr0 and t < ss0 %}
            {% set day_start = sr0 %}
            {% set day_end = ss0 %}
            {% set d = (t - day_start) / (day_end - day_start) %}
            {% set d = [0, [d, 1] | min] | max %}
            {{ (1 - ((2 * d - 1) ** 2)) | float(0) }}
          {% elif t >= sr_prev and t < ss_prev %}
            {% set day_start = sr_prev %}
            {% set day_end = ss_prev %}
            {% set d = (t - day_start) / (day_end - day_start) %}
            {% set d = [0, [d, 1] | min] | max %}
            {{ (1 - ((2 * d - 1) ** 2)) | float(0) }}
          {% elif t < sr0 %}
            {% set night_start = ss_prev %}
            {% set night_end = sr0 %}
            {% set n = (t - night_start) / (night_end - night_start) %}
            {% set n = [0, [n, 1] | min] | max %}
            {{ (-(1 - ((2 * n - 1) ** 2))) | float(0) }}
          {% else %}
            {% set night_start = ss0 %}
            {% set night_end = sr0 + 86400 %}
            {% set n = (t - night_start) / (night_end - night_start) %}
            {% set n = [0, [n, 1] | min] | max %}
            {{ (-(1 - ((2 * n - 1) ** 2))) | float(0) }}
          {% endif %}
        {% else %}
          0
        {% endif %}
      adaptive_curve_factor: >
        {% set p = sun_position | float(0) %}
        {% if p > 0 %}
          {% set s0 = p * p * p * ((p * ((6 * p) - 15)) + 10) %}
          {{ s0 ** (brightness_curve_gamma | float(1.5)) }}
        {% else %}
          0
        {% endif %}
      target_brightness: >
        {% set b_min = [b_night | float(1), b_day | float(100)] | min %}
        {% set b_max = [b_night | float(1), b_day | float(100)] | max %}
        {% set f = adaptive_curve_factor | float(0) %}
        {{ (b_min + (b_max - b_min) * f) | round(0) | int }}
      target_kelvin: >
        {% set k_min = [k_night | float(2200), k_day | float(5000)] | min %}
        {% set k_max = [k_night | float(2200), k_day | float(5000)] | max %}
        {% set f = adaptive_curve_factor | float(0) %}
        {{ (k_min + (k_max - k_min) * f) | round(0) | int }}

  - repeat:
      for_each: "{{ target_lights_to_update }}"
      sequence:
        - variables:
            modes: "{{ state_attr(repeat.item, 'supported_color_modes') or [] }}"
            modes_count: "{{ modes | count }}"
            min_k: "{{ state_attr(repeat.item, 'min_color_temp_kelvin') | float(0) }}"
            max_k: "{{ state_attr(repeat.item, 'max_color_temp_kelvin') | float(0) }}"
            # On periodic ticks, alternate between brightness and temperature updates.
            tick_updates_brightness: "{{ trigger.id == 'tick' and ((now_ts | int(0) // 300) % 2 == 0) }}"
            # If a light was turned on very recently, bypass alternation once.
            # This prevents keeping a stale brightness or color right after power-on.
            recently_turned_on: >
              {% set last_changed_ts = as_timestamp(states[repeat.item].last_changed) | float(0) %}
              {{ is_state(repeat.item, 'on') and ((now_ts | float(0)) - last_changed_ts) < 20 }}
            has_brightness_attr: "{{ state_attr(repeat.item, 'brightness') is not none }}"
            has_ct_kelvin_attr: "{{ state_attr(repeat.item, 'color_temp_kelvin') is not none }}"
            has_ct_attr: "{{ state_attr(repeat.item, 'color_temp') is not none }}"
            onoff_only: "{{ (modes_count == 1) and (modes[0] == 'onoff') }}"
            supports_ct: >
              {{ 'color_temp' in modes
                 or (min_k > 0 and max_k > 0)
                 or has_ct_kelvin_attr
                 or has_ct_attr }}
            # In Z2M/groups, supported_color_modes can be empty or partial.
            # Default to brightness-capable unless explicitly onoff-only.
            supports_brightness: >
              {{ has_brightness_attr
                 or (modes_count == 0)
                 or not onoff_only }}
            clamped_kelvin: >
              {% if min_k > 0 and max_k > 0 %}
                {{ [min_k, [target_kelvin | float(0), max_k] | min] | max | round(0) | int }}
              {% else %}
                {{ target_kelvin | int(0) }}
              {% endif %}
        - choose:
            - conditions:
                - condition: template
                  value_template: >
                    {{ trigger.id == 'tick'
                       and supports_brightness
                       and supports_ct
                       and recently_turned_on }}
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: "{{ repeat.item }}"
                  data:
                    transition: 10
                    brightness_pct: "{{ target_brightness | int(0) }}"
                    color_temp_kelvin: "{{ clamped_kelvin | int(0) }}"
            - conditions:
                - condition: template
                  value_template: >
                    {{ trigger.id == 'tick'
                       and supports_brightness
                       and supports_ct
                       and not recently_turned_on
                       and tick_updates_brightness }}
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: "{{ repeat.item }}"
                  data:
                    transition: 10
                    brightness_pct: "{{ target_brightness | int(0) }}"
            - conditions:
                - condition: template
                  value_template: >
                    {{ trigger.id == 'tick'
                       and supports_brightness
                       and supports_ct
                       and not recently_turned_on
                       and not tick_updates_brightness }}
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: "{{ repeat.item }}"
                  data:
                    transition: 10
                    color_temp_kelvin: "{{ clamped_kelvin | int(0) }}"
            - conditions:
                - condition: template
                  value_template: "{{ supports_brightness and supports_ct }}"
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: "{{ repeat.item }}"
                  data:
                    transition: 10
                    brightness_pct: "{{ target_brightness | int(0) }}"
                    color_temp_kelvin: "{{ clamped_kelvin | int(0) }}"
            - conditions:
                - condition: template
                  value_template: "{{ supports_brightness }}"
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: "{{ repeat.item }}"
                  data:
                    transition: 10
                    brightness_pct: "{{ target_brightness | int(0) }}"
            - conditions:
                - condition: template
                  value_template: "{{ supports_ct }}"
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: "{{ repeat.item }}"
                  data:
                    transition: 10
                    color_temp_kelvin: "{{ clamped_kelvin | int(0) }}"
          default:
            - service: light.turn_on
              target:
                entity_id: "{{ repeat.item }}"
              data:
                transition: 10
